'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Plus, X } from 'lucide-react';
import { toast } from 'sonner';
import { administrationApi, membersApi, type Fine, type Member } from '@/lib/api';

const reasons = ['Retard de paiement', 'Absence', 'Comportement', 'Autre'];
const statusLabel: Record<string, string> = { UNPAID: 'À régler', PAID: 'Réglée', CANCELLED: 'Annulée' };
const date = (value: string | null) => value ? new Date(value).toLocaleDateString('fr-FR', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

export default function AmendesPage() {
  const [fines, setFines] = useState<Fine[]>([]); const [members, setMembers] = useState<Member[]>([]);
  const [show, setShow] = useState(false); const [statusFilter, setStatusFilter] = useState('ALL'); const [reasonFilter, setReasonFilter] = useState('ALL'); const [memberFilter, setMemberFilter] = useState('ALL');
  const [memberId, setMemberId] = useState(''); const [reason, setReason] = useState(reasons[0]); const [amount, setAmount] = useState(0); const [note, setNote] = useState('');
  const load = () => administrationApi.fines().then(setFines).catch((e) => toast.error(e.message));
  useEffect(() => { load(); membersApi.list().then(setMembers).catch(() => setMembers([])); }, []);
  const visible = useMemo(() => fines.filter((fine) => (statusFilter === 'ALL' || fine.status === statusFilter) && (reasonFilter === 'ALL' || fine.reason === reasonFilter) && (memberFilter === 'ALL' || fine.member.id === memberFilter)), [fines, statusFilter, reasonFilter, memberFilter]);
  function openWizard() { setMemberId(''); setReason(reasons[0]); setAmount(0); setNote(''); setShow(true); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!memberId || amount <= 0) return; try { await administrationApi.createFine({ memberId, reason, amount, note }); toast.success('Amende enregistrée'); setShow(false); setMemberId(''); setAmount(0); setNote(''); load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Erreur'); } }

  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold text-slate-900">Amendes</h1><p className="mt-1 text-sm text-slate-500">Suivi des pénalités et des règlements.</p></div><button className="btn-primary flex items-center gap-2" onClick={openWizard}><Plus size={18} />Nouvelle amende</button></header>
    {show && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="fine-title"><form onSubmit={submit} className="w-full max-w-2xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-2xl"><div className="flex items-start justify-between px-7 py-6"><div><h2 id="fine-title" className="font-serif text-3xl text-slate-900">Nouvelle amende</h2><p className="mt-2 text-sm text-slate-500">Créer une obligation de paiement pour un membre.</p></div><button type="button" onClick={() => setShow(false)} aria-label="Fermer" className="rounded-lg p-2 text-slate-600 hover:bg-slate-100"><X size={24}/></button></div><div className="space-y-5 px-7 pb-7"><label className="block text-sm font-semibold text-slate-800">Membre<select required className="input-field mt-2 w-full" value={memberId} onChange={(e) => setMemberId(e.target.value)}><option value="">Sélectionner un membre…</option>{members.map((m) => <option key={m.id} value={m.id}>{m.firstName} {m.lastName} — {m.phone}</option>)}</select></label><label className="block text-sm font-semibold text-slate-800">Motif<select className="input-field mt-2 w-full" value={reason} onChange={(e) => setReason(e.target.value)}>{reasons.map((r) => <option key={r}>{r}</option>)}</select></label><label className="block text-sm font-semibold text-slate-800">Montant (F CFA)<input required min="1" type="number" className="input-field mt-2 w-full" value={amount || ''} onChange={(e) => setAmount(Number(e.target.value))} placeholder="0" /></label><label className="block text-sm font-semibold text-slate-800">Note <span className="font-normal text-slate-400">(facultative)</span><textarea className="input-field mt-2 min-h-24 w-full" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Ajouter un détail si nécessaire…" /></label></div><div className="flex justify-end gap-3 border-t border-slate-100 bg-slate-50 px-7 py-5"><button type="button" onClick={() => setShow(false)} className="rounded-xl border border-slate-300 bg-white px-5 py-2.5 font-semibold text-slate-700">Annuler</button><button type="submit" disabled={!memberId || amount <= 0} className="rounded-xl bg-[var(--sky-blue)] px-5 py-2.5 font-semibold text-white disabled:opacity-50">Créer l&apos;amende</button></div></form></div>}
    <section className="card flex flex-wrap gap-2 p-4"><select aria-label="Filtrer par statut" className="input-field w-full sm:w-auto sm:min-w-40" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="ALL">Tous les statuts</option><option value="UNPAID">À régler</option><option value="PAID">Réglées</option><option value="CANCELLED">Annulées</option></select><select aria-label="Filtrer par motif" className="input-field w-full sm:w-auto sm:min-w-44" value={reasonFilter} onChange={(e) => setReasonFilter(e.target.value)}><option value="ALL">Tous les motifs</option>{reasons.map((r) => <option key={r} value={r}>{r}</option>)}</select><select aria-label="Filtrer par membre" className="input-field w-full sm:w-auto sm:min-w-52" value={memberFilter} onChange={(e) => setMemberFilter(e.target.value)}><option value="ALL">Sélectionner un membre…</option>{members.map((m) => <option key={m.id} value={m.id}>{m.firstName} {m.lastName}</option>)}</select></section>
    <section className="card overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Membre</th><th className="px-5 py-3">Motif</th><th className="px-5 py-3">Montant</th><th className="px-5 py-3">Réglée le</th><th className="px-5 py-3">Statut</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody>{visible.map((fine) => <tr key={fine.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-5 py-3 text-slate-500">{date(fine.createdAt)}</td><td className="px-5 py-3 font-medium">{fine.member.firstName} {fine.member.lastName}</td><td className="px-5 py-3 text-slate-500">{fine.reason}</td><td className="px-5 py-3 font-medium">{Number(fine.amount).toLocaleString('fr-FR')} F</td><td className="px-5 py-3 text-slate-500">{date(fine.paidAt)}</td><td className="px-5 py-3"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${fine.status === 'PAID' ? 'bg-blue-50 text-blue-700' : fine.status === 'CANCELLED' ? 'bg-slate-100 text-slate-500' : 'bg-amber-50 text-amber-700'}`}>{statusLabel[fine.status]}</span></td><td className="px-5 py-3 text-right">{fine.status === 'UNPAID' ? <span className="inline-flex gap-3"><button title="Marquer comme réglée" className="font-medium text-emerald-700 hover:underline" onClick={() => administrationApi.settleFine(fine.id).then(() => { toast.success('Règlement encaissé'); load(); })}>Régler</button><button title="Annuler cette amende" className="text-red-600 hover:underline" onClick={() => administrationApi.cancelFine(fine.id).then(load)}>Annuler</button></span> : <span className="text-slate-400">—</span>}</td></tr>)}</tbody></table></div>{visible.length === 0 && <p className="p-10 text-center text-slate-500">Aucune amende.</p>}</section>
  </div>;
}
