'use client';

import { FormEvent, useEffect, useState } from 'react';
import { toast } from 'sonner';
import { administrationApi, membersApi, type ContributionExemption, type Member } from '@/lib/api';

export default function ExonerationsPage(){
  const now=new Date(); const [rows,setRows]=useState<ContributionExemption[]>([]); const [members,setMembers]=useState<Member[]>([]);
  const [memberId,setMemberId]=useState(''); const [year,setYear]=useState(now.getFullYear()); const [month,setMonth]=useState(now.getMonth()+1); const [reason,setReason]=useState('');
  const load=()=>administrationApi.exemptions(undefined,year).then(setRows).catch(e=>toast.error(e.message));
  useEffect(()=>{load();membersApi.list().then(setMembers);},[year]);
  async function submit(e:FormEvent){e.preventDefault();try{await administrationApi.createExemption({memberId,periodYear:year,periodMonth:month,reason});toast.success('Mois exonéré');setReason('');load();}catch(err){toast.error(err instanceof Error?err.message:'Erreur');}}
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Mois exonérés</h1><p className="mt-1 text-sm text-slate-500">Les mois exonérés ne génèrent ni retard, ni suspension.</p></div><form onSubmit={submit} className="card grid gap-4 md:grid-cols-4"><label className="text-sm font-medium md:col-span-2">Membre<select className="input-field mt-1.5 w-full" required value={memberId} onChange={e=>setMemberId(e.target.value)}><option value="">Choisir…</option>{members.filter(m=>m.role!=='ADMIN').map(m=><option key={m.id} value={m.id}>{m.firstName} {m.lastName}</option>)}</select></label><label className="text-sm font-medium">Mois<select className="input-field mt-1.5 w-full" value={month} onChange={e=>setMonth(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{new Date(2020,i).toLocaleString('fr-FR',{month:'long'})}</option>)}</select></label><label className="text-sm font-medium">Année<input type="number" className="input-field mt-1.5 w-full" value={year} onChange={e=>setYear(Number(e.target.value))}/></label><label className="text-sm font-medium md:col-span-3">Motif (facultatif)<input className="input-field mt-1.5 w-full" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Blessure, congé exceptionnel…"/></label><button className="btn-primary self-end">Ajouter</button></form><div className="card overflow-hidden p-0"><table className="w-full text-left text-sm"><thead><tr className="bg-sky-50"><th className="p-4">Membre</th><th className="p-4">Période</th><th className="p-4">Motif</th><th className="p-4"></th></tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r.id}><td className="p-4 font-medium">{r.member.firstName} {r.member.lastName}</td><td className="p-4">{new Date(r.periodYear,r.periodMonth-1).toLocaleString('fr-FR',{month:'long',year:'numeric'})}</td><td className="p-4 text-slate-500">{r.reason||'—'}</td><td className="p-4 text-right"><button className="text-red-600" onClick={()=>administrationApi.deleteExemption(r.id).then(load)}>Retirer</button></td></tr>)}</tbody></table>{rows.length===0&&<p className="p-10 text-center text-slate-500">Aucune exonération en {year}.</p>}</div></div>;
}
